In [1]:
# pip install pandas

In [1]:
import pandas as pd

In [3]:
#series=1D labelled array
#DataFrame=2D labelled array(eg:table)

In [4]:
info={
    "Name":["Yash","Monty","Gaurav","Digvijay"],
    "CGPA":[9.5,8,9,10]
}
df=pd.DataFrame(info)
print(df)

       Name  CGPA
0      Yash   9.5
1     Monty   8.0
2    Gaurav   9.0
3  Digvijay  10.0

In [5]:
df

       Name  CGPA
0      Yash   9.5
1     Monty   8.0
2    Gaurav   9.0
3  Digvijay  10.0

In [6]:
#series
s=pd.Series([1,2,3,4,5])
print(type(s),s)

#index
print(s[0])
print(s[3])

<class 'pandas.core.series.Series'> 0    1
1    2
2    3
3    4
4    5
dtype: int64
1
4

In [7]:
s=pd.Series([23,24,25,22],index=["Adam","Eve","Bob","Charlie"])
print(s)
print(s["Bob"])
# print(s[0])
print(s.index)

Adam       23
Eve        24
Bob        25
Charlie    22
dtype: int64
25
Index(['Adam', 'Eve', 'Bob', 'Charlie'], dtype='object')

In [8]:
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([10,20,30,40,50])
s1[1]=100
changed_s1=s1.drop(0)
print(changed_s1)
print(s1)

1    100
2      3
3      4
4      5
dtype: int64
0      1
1    100
2      3
3      4
4      5
dtype: int64

In [9]:
#DataFrame
info={
    "Name":["Yash","Digvijay","Monty","Sanjay"],
    "Age":[22,23,17,22],
    "cgpa":[9.4,10,9.8,9]
}
df=pd.DataFrame(info)
print(df,type(df))
print(df.index)
print(df.columns)

       Name  Age  cgpa
0      Yash   22   9.4
1  Digvijay   23  10.0
2     Monty   17   9.8
3    Sanjay   22   9.0 <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=4, step=1)
Index(['Name', 'Age', 'cgpa'], dtype='object')

In [10]:
df=pd.DataFrame([["Adam",23],["Bob",22],["Eve"]],columns=["Name","Age"])
df

   Name   Age
0  Adam  23.0
1   Bob  22.0
2   Eve   NaN

In [11]:
import numpy as np
np_arr=np.array([[1,2,3],[4,5,6]])
df=pd.DataFrame(np_arr,columns=["A","B","C"])
df

   A  B  C
0  1  2  3
1  4  5  6

In [12]:
#csv data
df=pd.read_csv("employee_data.csv")
print(df,type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   60000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [13]:
#json data
# df=pd.read_json("employee_data.json")
# print(df)
# df

In [14]:
#Methods
print(df.head())#starting 5 rows
df.head()

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [15]:
df.tail()#last 5 rows

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   60000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [16]:
df.tail(2)#last 2 rows

   ID   Name  Age Department  Salary
8   9    Ian   35         IT   75000
9  10  Julia   30    Finance   60000

In [17]:
df.sample(5)#random row

   ID   Name  Age Department  Salary
1   2    Bob   32         IT   72000
3   4  David   45  Marketing   91000
5   6  Frank   29    Finance   60000
0   1  Alice   25         HR   55000
6   7  Grace   41         HR   82000

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [19]:
df.shape #tuple of 10 rows, 5 columns (no brackets BTW)

(10, 5)

In [20]:
df.describe() #stats for numerical vlaues

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  65500.000000
std     3.02765   6.674162  14431.832101
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  56250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [21]:
df.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

In [22]:
df.nunique() #no. of unique val in each col

ID            10
Name          10
Age           10
Department     4
Salary         9
dtype: int64

In [23]:
#AQI Data set
df=pd.read_csv("globalAirQuality.csv")
df.head()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017

In [24]:
df.tail()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [25]:
df.describe()#to get some summary or insights

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [26]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [27]:
#selecting the data
df["city"]
df[["city","aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [28]:
df.loc[0] #(location ) - label based access

timestamp      2025-11-04 18:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                               50.295
pm10                              108.938
no2                                27.998
so2                                 6.539
o3                                 52.568
co                                  1.096
aqi                                   108
temperature                        18.504
humidity                           70.168
wind_speed                          3.725
Name: 0, dtype: object

In [29]:
df.loc[0:2]# 2nd index also included

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650

In [30]:
#LOC / iLOC
df.iloc[2]#index location
df.iloc[0:2] #2 is not included

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969

In [31]:
df.loc[0:2,["city","aqi"]]

       city  aqi
0  New York  108
1  New York   90
2  New York   84

In [32]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [33]:
# df.iloc[0:2,["city","aqi"]] (iloc requires numeric indexers, got ['city' 'aqi'])

In [34]:
df.columns

Index(['timestamp', 'country', 'city', 'latitude', 'longitude', 'pm25', 'pm10',
       'no2', 'so2', 'o3', 'co', 'aqi', 'temperature', 'humidity',
       'wind_speed'],
      dtype='object')

In [35]:
df.iloc[0:3,1:5]

  country      city  latitude  longitude
0      US  New York    40.713    -74.006
1      US  New York    40.713    -74.006
2      US  New York    40.713    -74.006

In [36]:
df.loc[0:2,['country', 'city', 'latitude', 'longitude']]

  country      city  latitude  longitude
0      US  New York    40.713    -74.006
1      US  New York    40.713    -74.006
2      US  New York    40.713    -74.006

In [37]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [38]:
#AT and iAT
df.at[0,"city"]
df.iat[0,2]

'New York'

In [39]:
cities=df["city"]#view
cities[0]="New York"#original data is changed

C:\Users\yasha\AppData\Local\Temp\ipykernel_16788\2801835400.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cities[0]="New York"#original data is changed

In [40]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [41]:
cities=df["city"].copy() #a copy is created to preserve original data
cities[0]="Mumbai" # copy
cities

0          Mumbai
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object

In [42]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [43]:
#Filtering Data
df[(df["aqi"]>100)&(df["temperature"]>30)]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
14,2025-11-05 08:25:17.554219,US,New York,40.713,-74.006,38.815,121.394,25.969,4.112,44.730,1.124,121,34.481,81.790,3.576
17,2025-11-05 11:25:17.554219,US,New York,40.713,-74.006,63.552,57.838,13.754,4.427,42.251,0.997,127,36.193,62.906,7.097
25,2025-11-05 19:25:17.554219,US,New York,40.713,-74.006,56.954,75.045,29.837,9.541,54.198,1.170,113,31.289,43.279,5.264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17947,2025-11-17 13:25:17.554219,CH,Zurich,47.377,8.542,53.938,75.183,16.255,7.263,67.244,0.457,107,32.584,81.544,7.101
17950,2025-11-17 16:25:17.554219,CH,Zurich,47.377,8.542,70.255,60.620,32.081,2.065,47.803,0.852,140,36.885,34.173,1.748
17975,2025-11-18 17:25:17.554219,CH,Zurich,47.377,8.542,33.406,98.160,44.654,0.807,45.160,0.737,111,30.761,76.073,3.570
17976,2025-11-18 18:25:17.554219,CH,Zurich,47.377,8.542,73.493,89.558,9.313,4.768,51.505,0.745,146,30.909,81.573,1.024
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787

In [44]:
aqi_data=df[(df["aqi"]>100)&(df["temperature"]>30)][["city","aqi"]]
print(aqi_data.iloc[0])
aqi_data.loc[6]

city    New York
aqi          155
Name: 6, dtype: object

city    New York
aqi          155
Name: 6, dtype: object

In [45]:
 #query method
df.query("aqi>100 & temperature>30")[["city","aqi"]]

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [46]:
aqi_val=100# using pthon varialble
df.query("aqi>@aqi_val")# returning a COPY btw
#but you should still create a copy i.e.
aqi_value=df.query("aqi>100 & temperature>30")[["city","aqi"]].copy()
aqi_value

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [47]:
# Data Cleaning

In [48]:
#missing value

In [2]:
df=pd.read_csv("raw_data.csv")
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [50]:
df.isnull()

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [51]:
df.isna()# same same but diffe

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [52]:
df.isnull().sum() #count how many missing val

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [53]:
df.dropna(axis=1)# drop entire row

    id
0    1
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10

In [54]:
df.fillna(0)# fill missing val with 0

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   0.0  Canada   Female  62000.0
3    3          Alex   0.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      0.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6             0  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0       0     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   0.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA        0  58000.0

In [55]:
df.fillna("Badmoss")

    id          name      age  country   gender   income
0    1      John Doe     29.0      USA     Male  55000.0
1    1      John Doe     29.0      USA     Male  55000.0
2    2    Jane Smith  Badmoss   Canada   Female  62000.0
3    3          Alex  Badmoss      USA  Unknown  47000.0
4    4  Maria Garcia     34.0    Spain   Female  Badmoss
5    5        Li Wei     27.0    China     Male  51000.0
6    6       Badmoss     45.0    India   Female  73000.0
7    7    Ahmed Khan     38.0  Badmoss     Male  68000.0
8    8    Rachel Lee     29.0      USA   Female  62000.0
9    9   Carlos Ruiz  Badmoss   Mexico     Male  45000.0
10  10   Emily Davis     31.0      USA  Badmoss  58000.0

In [56]:
cleaned=df.copy()
age_mean=cleaned["age"].mean()
cleaned["age"]=cleaned["age"].fillna(age_mean.round())

In [57]:
cleaned

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  33.0  Canada   Female  62000.0
3    3          Alex  33.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  33.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [58]:
df=df.ffill()#forward fill

In [59]:
# df.bfill()

In [60]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  29.0  Canada   Female  62000.0
3    3          Alex  29.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6        Li Wei  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0   India     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     Male  58000.0

In [61]:
#Handle Duplicate Value
df.duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [62]:
df["country"].duplicated()

0     False
1      True
2     False
3      True
4     False
5     False
6     False
7      True
8      True
9     False
10     True
Name: country, dtype: bool

In [63]:
df[["country","gender"]].duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
dtype: bool

In [64]:
df.drop_duplicates()#dont reflect in OG data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  29.0  Canada   Female  62000.0
3    3          Alex  29.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6        Li Wei  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0   India     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     Male  58000.0

In [65]:
df2=df.copy()
df2.drop_duplicates(inplace=True)
df2

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  29.0  Canada   Female  62000.0
3    3          Alex  29.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6        Li Wei  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0   India     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     Male  58000.0

In [66]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  29.0  Canada   Female  62000.0
3    3          Alex  29.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6        Li Wei  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0   India     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     Male  58000.0

In [67]:
#Data types
df.dtypes

id           int64
name        object
age        float64
country     object
gender      object
income     float64
dtype: object

In [68]:
df2=df.copy()
df2=df2.fillna(0)
df2["age"]=df2["age"].astype("int64")
df2.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [69]:
df2

    id          name  age country   gender   income
0    1      John Doe   29     USA     Male  55000.0
1    1      John Doe   29     USA     Male  55000.0
2    2    Jane Smith   29  Canada   Female  62000.0
3    3          Alex   29     USA  Unknown  47000.0
4    4  Maria Garcia   34   Spain   Female  47000.0
5    5        Li Wei   27   China     Male  51000.0
6    6        Li Wei   45   India   Female  73000.0
7    7    Ahmed Khan   38   India     Male  68000.0
8    8    Rachel Lee   29     USA   Female  62000.0
9    9   Carlos Ruiz   29  Mexico     Male  45000.0
10  10   Emily Davis   31     USA     Male  58000.0

In [70]:
aqi_data=pd.read_csv("globalAirQuality.csv")
aqi_data

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [71]:
date_str=pd.Series([pd.to_datetime("2026-06-05")])
print(type(date_str))
type(date_str.dtypes)

<class 'pandas.core.series.Series'>

numpy.dtypes.DateTime64DType

In [72]:
aqi_data["timestamp"]=pd.to_datetime(aqi_data["timestamp"])
aqi_data["timestamp"].dtypes

dtype('<M8[ns]')

In [73]:
#Handle Strings 
df.dtypes
df["gender"].str.lower()
df["gender"].str.upper()
df["gender"].str.capitalize()

0        Male
1        Male
2      Female
3     Unknown
4      Female
5        Male
6      Female
7        Male
8      Female
9        Male
10       Male
Name: gender, dtype: object

In [74]:
df["name"].str.split(" ")
# the space is traced to se[erate the values

0         [John, Doe]
1         [John, Doe]
2       [Jane, Smith]
3              [Alex]
4     [Maria, Garcia]
5           [Li, Wei]
6           [Li, Wei]
7       [Ahmed, Khan]
8       [Rachel, Lee]
9      [Carlos, Ruiz]
10     [Emily, Davis]
Name: name, dtype: object

In [75]:
df["country"].str.contains("USA")
df["country"].str.contains("india",case=False) #no more case sensitive

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7      True
8     False
9     False
10    False
Name: country, dtype: bool

In [76]:
#Feature Engineering
df2=df.copy()
df2["tax"]=df2["income"].apply(lambda x:"20%" if x>=50000 else "10%")
df2

    id          name   age country   gender   income  tax
0    1      John Doe  29.0     USA     Male  55000.0  20%
1    1      John Doe  29.0     USA     Male  55000.0  20%
2    2    Jane Smith  29.0  Canada   Female  62000.0  20%
3    3          Alex  29.0     USA  Unknown  47000.0  10%
4    4  Maria Garcia  34.0   Spain   Female  47000.0  10%
5    5        Li Wei  27.0   China     Male  51000.0  20%
6    6        Li Wei  45.0   India   Female  73000.0  20%
7    7    Ahmed Khan  38.0   India     Male  68000.0  20%
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0  10%
10  10   Emily Davis  31.0     USA     Male  58000.0  20%

In [77]:
gender_map={"Male":"M","Female":"F","Unknown":"U"}
df2["gender"]=df2["gender"].map(gender_map)

In [78]:
df2

    id          name   age country gender   income  tax
0    1      John Doe  29.0     USA      M  55000.0  20%
1    1      John Doe  29.0     USA      M  55000.0  20%
2    2    Jane Smith  29.0  Canada      F  62000.0  20%
3    3          Alex  29.0     USA      U  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F  47000.0  10%
5    5        Li Wei  27.0   China      M  51000.0  20%
6    6        Li Wei  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0   India      M  68000.0  20%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
9    9   Carlos Ruiz  29.0  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0     USA      M  58000.0  20%

In [79]:
df2=df2.assign(new_income=df2["income"]*1.1)

In [80]:
#replace(old,new)
df2["country"]=df2["country"].replace("USA","US")

In [81]:
df2

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0      US      M  55000.0  20%     60500.0
1    1      John Doe  29.0      US      M  55000.0  20%     60500.0
2    2    Jane Smith  29.0  Canada      F  62000.0  20%     68200.0
3    3          Alex  29.0      US      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F  47000.0  10%     51700.0
5    5        Li Wei  27.0   China      M  51000.0  20%     56100.0
6    6        Li Wei  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0   India      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
9    9   Carlos Ruiz  29.0  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0      US      M  58000.0  20%     63800.0

In [82]:
#rename(column={old:new})
df2.columns=["Id","Name","Age","Countrg","Gender","Income","Tax","New_Income"]
df2.rename(columns={"Income":"Salary"})
df2.rename(index={1:"First"})
df2.sort_values("Income")
df2.sort_values(["Income","Age"])
sorted_df=df2.sort_values("Income")
sorted_df.sort_index()

#reset
sorted_df.reset_index()# OG index is still preserved
sorted_df.reset_index(drop=True)

    Id          Name   Age Countrg Gender   Income  Tax  New_Income
0    9   Carlos Ruiz  29.0  Mexico      M  45000.0  10%     49500.0
1    3          Alex  29.0      US      U  47000.0  10%     51700.0
2    4  Maria Garcia  34.0   Spain      F  47000.0  10%     51700.0
3    5        Li Wei  27.0   China      M  51000.0  20%     56100.0
4    1      John Doe  29.0      US      M  55000.0  20%     60500.0
5    1      John Doe  29.0      US      M  55000.0  20%     60500.0
6   10   Emily Davis  31.0      US      M  58000.0  20%     63800.0
7    2    Jane Smith  29.0  Canada      F  62000.0  20%     68200.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
9    7    Ahmed Khan  38.0   India      M  68000.0  20%     74800.0
10   6        Li Wei  45.0   India      F  73000.0  20%     80300.0

In [83]:
#Ranking
sorted_df["Ranking"]=sorted_df["Income"].rank(ascending=False,method="dense")
sorted_df

    Id          Name   Age Countrg Gender   Income  Tax  New_Income  Ranking
9    9   Carlos Ruiz  29.0  Mexico      M  45000.0  10%     49500.0      8.0
3    3          Alex  29.0      US      U  47000.0  10%     51700.0      7.0
4    4  Maria Garcia  34.0   Spain      F  47000.0  10%     51700.0      7.0
5    5        Li Wei  27.0   China      M  51000.0  20%     56100.0      6.0
0    1      John Doe  29.0      US      M  55000.0  20%     60500.0      5.0
1    1      John Doe  29.0      US      M  55000.0  20%     60500.0      5.0
10  10   Emily Davis  31.0      US      M  58000.0  20%     63800.0      4.0
2    2    Jane Smith  29.0  Canada      F  62000.0  20%     68200.0      3.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0      3.0
7    7    Ahmed Khan  38.0   India      M  68000.0  20%     74800.0      2.0
6    6        Li Wei  45.0   India      F  73000.0  20%     80300.0      1.0

In [84]:

sorted_df["Ranking"]=sorted_df["Income"].rank(ascending=False,method="max")
sorted_df

    Id          Name   Age Countrg Gender   Income  Tax  New_Income  Ranking
9    9   Carlos Ruiz  29.0  Mexico      M  45000.0  10%     49500.0     11.0
3    3          Alex  29.0      US      U  47000.0  10%     51700.0     10.0
4    4  Maria Garcia  34.0   Spain      F  47000.0  10%     51700.0     10.0
5    5        Li Wei  27.0   China      M  51000.0  20%     56100.0      8.0
0    1      John Doe  29.0      US      M  55000.0  20%     60500.0      7.0
1    1      John Doe  29.0      US      M  55000.0  20%     60500.0      7.0
10  10   Emily Davis  31.0      US      M  58000.0  20%     63800.0      5.0
2    2    Jane Smith  29.0  Canada      F  62000.0  20%     68200.0      4.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0      4.0
7    7    Ahmed Khan  38.0   India      M  68000.0  20%     74800.0      2.0
6    6        Li Wei  45.0   India      F  73000.0  20%     80300.0      1.0

In [85]:
#Columns
sorted_df[["Id","Name","Age","Countrg","Gender","Income","New_Income","Tax"]]

    Id          Name   Age Countrg Gender   Income  New_Income  Tax
9    9   Carlos Ruiz  29.0  Mexico      M  45000.0     49500.0  10%
3    3          Alex  29.0      US      U  47000.0     51700.0  10%
4    4  Maria Garcia  34.0   Spain      F  47000.0     51700.0  10%
5    5        Li Wei  27.0   China      M  51000.0     56100.0  20%
0    1      John Doe  29.0      US      M  55000.0     60500.0  20%
1    1      John Doe  29.0      US      M  55000.0     60500.0  20%
10  10   Emily Davis  31.0      US      M  58000.0     63800.0  20%
2    2    Jane Smith  29.0  Canada      F  62000.0     68200.0  20%
8    8    Rachel Lee  29.0      US      F  62000.0     68200.0  20%
7    7    Ahmed Khan  38.0   India      M  68000.0     74800.0  20%
6    6        Li Wei  45.0   India      F  73000.0     80300.0  20%

In [86]:
#task
df=df2.copy()
new_col_order=[col for col in df2.columns if col !="Id"]+["Id"]
print(new_col_order)
df2[new_col_order]

['Name', 'Age', 'Countrg', 'Gender', 'Income', 'Tax', 'New_Income', 'Id']

            Name   Age Countrg Gender   Income  Tax  New_Income  Id
0       John Doe  29.0      US      M  55000.0  20%     60500.0   1
1       John Doe  29.0      US      M  55000.0  20%     60500.0   1
2     Jane Smith  29.0  Canada      F  62000.0  20%     68200.0   2
3           Alex  29.0      US      U  47000.0  10%     51700.0   3
4   Maria Garcia  34.0   Spain      F  47000.0  10%     51700.0   4
5         Li Wei  27.0   China      M  51000.0  20%     56100.0   5
6         Li Wei  45.0   India      F  73000.0  20%     80300.0   6
7     Ahmed Khan  38.0   India      M  68000.0  20%     74800.0   7
8     Rachel Lee  29.0      US      F  62000.0  20%     68200.0   8
9    Carlos Ruiz  29.0  Mexico      M  45000.0  10%     49500.0   9
10   Emily Davis  31.0      US      M  58000.0  20%     63800.0  10

In [87]:
df2

    Id          Name   Age Countrg Gender   Income  Tax  New_Income
0    1      John Doe  29.0      US      M  55000.0  20%     60500.0
1    1      John Doe  29.0      US      M  55000.0  20%     60500.0
2    2    Jane Smith  29.0  Canada      F  62000.0  20%     68200.0
3    3          Alex  29.0      US      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F  47000.0  10%     51700.0
5    5        Li Wei  27.0   China      M  51000.0  20%     56100.0
6    6        Li Wei  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0   India      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
9    9   Carlos Ruiz  29.0  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0      US      M  58000.0  20%     63800.0

In [3]:
df2=df.copy()
df2

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [4]:
df2=df2.drop_duplicates()

In [11]:
df2=df2.fillna(0)
df2=df2.sort_values("income")
df2=df2.reset_index(drop=True)

In [13]:
df2.to_csv("sorted_data.csv")

In [14]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [34]:
#Grouping and Aggregation

df.groupby("country")["income"].mean()
df.groupby("country")["income"].min()
df.groupby("country")["income"].max()

df.groupby("gender")["income"].max()

df.groupby("country")["income"].agg(["mean","min","max"])
df.groupby("country")["income"].aggregate(["mean","min","max"])#same same but different
df.groupby("country")["income"].agg(avg_salary="mean",min_salary="min",max_salary="max")#rename the aggregate values

df.groupby("country").agg({
    "income":"mean",
    "age":"mean"
})

df.groupby("country").agg({
    "income":"max",
    "age":"mean"
})

df.groupby("country").agg(
    max_salary=("income","max"),
    avg_age=("age","mean")
)

         max_salary  avg_age
country
Canada      62000.0      NaN
China       51000.0     27.0
India       73000.0     45.0
Mexico      45000.0      NaN
Spain           NaN     34.0
USA         62000.0     29.5

In [ ]:
#Melt function
'''Melt-wide to long
    
    melt(
    id_vars(keep)
    value_vars(unpivot)
    var_name(new column name)
    value_name(new column value)
    )
    '''

In [38]:
df = pd.DataFrame({
"country": ["USA", "USA", "India", "India"],
"year": [2020, 2021, 2020, 2021],
"sales": [100, 120, 90, 110],
"profit": [20, 25, 18, 22],
"tax":[10,20,30,40]
})
df

  country  year  sales  profit  tax
0     USA  2020    100      20   10
1     USA  2021    120      25   20
2   India  2020     90      18   30
3   India  2021    110      22   40

In [44]:
melted_df=df.melt(
    id_vars=["country","year"],
    value_vars=["sales","profit"],
    var_name="matric",
    value_name="value"
)

In [45]:
melted_df

  country  year  matric  value
0     USA  2020   sales    100
1     USA  2021   sales    120
2   India  2020   sales     90
3   India  2021   sales    110
4     USA  2020  profit     20
5     USA  2021  profit     25
6   India  2020  profit     18
7   India  2021  profit     22

In [43]:
#Pivot function

#Pivot-Long to wide format
'''pivot(index,columns,values)'''

'pivot(index,columns,values)'

In [48]:
original=melted_df.pivot(
    index=["country","year"],
    columns="matric",
    values="value"
)

In [49]:
original

matric        profit  sales
country year
India   2020      18     90
        2021      22    110
USA     2020      20    100
        2021      25    120